/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoComandoAlternativo extends PComandoAlternativo
{
    private PIdAtribuicao _idAtribuicao_;
    private TFechaLinha _fechaLinha_;

    public AAtribuicaoComandoAlternativo()
    {
        // Constructor
    }

    public AAtribuicaoComandoAlternativo(
        @SuppressWarnings("hiding") PIdAtribuicao _idAtribuicao_,
        @SuppressWarnings("hiding") TFechaLinha _fechaLinha_)
    {
        // Constructor
        setIdAtribuicao(_idAtribuicao_);

        setFechaLinha(_fechaLinha_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoComandoAlternativo(
            cloneNode(this._idAtribuicao_),
            cloneNode(this._fechaLinha_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoComandoAlternativo(this);
    }

    public PIdAtribuicao getIdAtribuicao()
    {
        return this._idAtribuicao_;
    }

    public void setIdAtribuicao(PIdAtribuicao node)
    {
        if(this._idAtribuicao_ != null)
        {
            this._idAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idAtribuicao_ = node;
    }

    public TFechaLinha getFechaLinha()
    {
        return this._fechaLinha_;
    }

    public void setFechaLinha(TFechaLinha node)
    {
        if(this._fechaLinha_ != null)
        {
            this._fechaLinha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaLinha_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idAtribuicao_)
            + toString(this._fechaLinha_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idAtribuicao_ == child)
        {
            this._idAtribuicao_ = null;
            return;
        }

        if(this._fechaLinha_ == child)
        {
            this._fechaLinha_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idAtribuicao_ == oldChild)
        {
            setIdAtribuicao((PIdAtribuicao) newChild);
            return;
        }

        if(this._fechaLinha_ == oldChild)
        {
            setFechaLinha((TFechaLinha) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
