/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoEExpBooleanoE extends PExpBooleanoE
{
    private PExpBooleanoE _expBooleanoE_;
    private TE _e_;
    private PExpNegacao _expNegacao_;

    public ABooleanoEExpBooleanoE()
    {
        // Constructor
    }

    public ABooleanoEExpBooleanoE(
        @SuppressWarnings("hiding") PExpBooleanoE _expBooleanoE_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PExpNegacao _expNegacao_)
    {
        // Constructor
        setExpBooleanoE(_expBooleanoE_);

        setE(_e_);

        setExpNegacao(_expNegacao_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoEExpBooleanoE(
            cloneNode(this._expBooleanoE_),
            cloneNode(this._e_),
            cloneNode(this._expNegacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoEExpBooleanoE(this);
    }

    public PExpBooleanoE getExpBooleanoE()
    {
        return this._expBooleanoE_;
    }

    public void setExpBooleanoE(PExpBooleanoE node)
    {
        if(this._expBooleanoE_ != null)
        {
            this._expBooleanoE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoE_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PExpNegacao getExpNegacao()
    {
        return this._expNegacao_;
    }

    public void setExpNegacao(PExpNegacao node)
    {
        if(this._expNegacao_ != null)
        {
            this._expNegacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expNegacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoE_)
            + toString(this._e_)
            + toString(this._expNegacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoE_ == child)
        {
            this._expBooleanoE_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._expNegacao_ == child)
        {
            this._expNegacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoE_ == oldChild)
        {
            setExpBooleanoE((PExpBooleanoE) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._expNegacao_ == oldChild)
        {
            setExpNegacao((PExpNegacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
