/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoOuExpBooleanoEOu extends PExpBooleanoEOu
{
    private PExpBooleanoEOu _expBooleanoEOu_;
    private TOu _ou_;
    private PExpNegacao _expNegacao_;

    public ABooleanoOuExpBooleanoEOu()
    {
        // Constructor
    }

    public ABooleanoOuExpBooleanoEOu(
        @SuppressWarnings("hiding") PExpBooleanoEOu _expBooleanoEOu_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpNegacao _expNegacao_)
    {
        // Constructor
        setExpBooleanoEOu(_expBooleanoEOu_);

        setOu(_ou_);

        setExpNegacao(_expNegacao_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoOuExpBooleanoEOu(
            cloneNode(this._expBooleanoEOu_),
            cloneNode(this._ou_),
            cloneNode(this._expNegacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoOuExpBooleanoEOu(this);
    }

    public PExpBooleanoEOu getExpBooleanoEOu()
    {
        return this._expBooleanoEOu_;
    }

    public void setExpBooleanoEOu(PExpBooleanoEOu node)
    {
        if(this._expBooleanoEOu_ != null)
        {
            this._expBooleanoEOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoEOu_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpNegacao getExpNegacao()
    {
        return this._expNegacao_;
    }

    public void setExpNegacao(PExpNegacao node)
    {
        if(this._expNegacao_ != null)
        {
            this._expNegacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expNegacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoEOu_)
            + toString(this._ou_)
            + toString(this._expNegacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoEOu_ == child)
        {
            this._expBooleanoEOu_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expNegacao_ == child)
        {
            this._expNegacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoEOu_ == oldChild)
        {
            setExpBooleanoEOu((PExpBooleanoEOu) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expNegacao_ == oldChild)
        {
            setExpNegacao((PExpNegacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
