/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoOuExpBooleanoOu extends PExpBooleanoOu
{
    private PExpBooleanoOu _expBooleanoOu_;
    private TOu _ou_;
    private PExpBooleanoE _expBooleanoE_;

    public ABooleanoOuExpBooleanoOu()
    {
        // Constructor
    }

    public ABooleanoOuExpBooleanoOu(
        @SuppressWarnings("hiding") PExpBooleanoOu _expBooleanoOu_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpBooleanoE _expBooleanoE_)
    {
        // Constructor
        setExpBooleanoOu(_expBooleanoOu_);

        setOu(_ou_);

        setExpBooleanoE(_expBooleanoE_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoOuExpBooleanoOu(
            cloneNode(this._expBooleanoOu_),
            cloneNode(this._ou_),
            cloneNode(this._expBooleanoE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoOuExpBooleanoOu(this);
    }

    public PExpBooleanoOu getExpBooleanoOu()
    {
        return this._expBooleanoOu_;
    }

    public void setExpBooleanoOu(PExpBooleanoOu node)
    {
        if(this._expBooleanoOu_ != null)
        {
            this._expBooleanoOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoOu_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpBooleanoE getExpBooleanoE()
    {
        return this._expBooleanoE_;
    }

    public void setExpBooleanoE(PExpBooleanoE node)
    {
        if(this._expBooleanoE_ != null)
        {
            this._expBooleanoE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoOu_)
            + toString(this._ou_)
            + toString(this._expBooleanoE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoOu_ == child)
        {
            this._expBooleanoOu_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expBooleanoE_ == child)
        {
            this._expBooleanoE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoOu_ == oldChild)
        {
            setExpBooleanoOu((PExpBooleanoOu) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expBooleanoE_ == oldChild)
        {
            setExpBooleanoE((PExpBooleanoE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
