/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AComparacaoMaiorExpBooleanoCmpMaior extends PExpBooleanoCmpMaior
{
    private PExpBooleanoCmpMaior _expBooleanoCmpMaior_;
    private TMaior _maior_;
    private PExpBooleanoCmpMaiorIgual _expBooleanoCmpMaiorIgual_;

    public AComparacaoMaiorExpBooleanoCmpMaior()
    {
        // Constructor
    }

    public AComparacaoMaiorExpBooleanoCmpMaior(
        @SuppressWarnings("hiding") PExpBooleanoCmpMaior _expBooleanoCmpMaior_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExpBooleanoCmpMaiorIgual _expBooleanoCmpMaiorIgual_)
    {
        // Constructor
        setExpBooleanoCmpMaior(_expBooleanoCmpMaior_);

        setMaior(_maior_);

        setExpBooleanoCmpMaiorIgual(_expBooleanoCmpMaiorIgual_);

    }

    @Override
    public Object clone()
    {
        return new AComparacaoMaiorExpBooleanoCmpMaior(
            cloneNode(this._expBooleanoCmpMaior_),
            cloneNode(this._maior_),
            cloneNode(this._expBooleanoCmpMaiorIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparacaoMaiorExpBooleanoCmpMaior(this);
    }

    public PExpBooleanoCmpMaior getExpBooleanoCmpMaior()
    {
        return this._expBooleanoCmpMaior_;
    }

    public void setExpBooleanoCmpMaior(PExpBooleanoCmpMaior node)
    {
        if(this._expBooleanoCmpMaior_ != null)
        {
            this._expBooleanoCmpMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoCmpMaior_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExpBooleanoCmpMaiorIgual getExpBooleanoCmpMaiorIgual()
    {
        return this._expBooleanoCmpMaiorIgual_;
    }

    public void setExpBooleanoCmpMaiorIgual(PExpBooleanoCmpMaiorIgual node)
    {
        if(this._expBooleanoCmpMaiorIgual_ != null)
        {
            this._expBooleanoCmpMaiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoCmpMaiorIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoCmpMaior_)
            + toString(this._maior_)
            + toString(this._expBooleanoCmpMaiorIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoCmpMaior_ == child)
        {
            this._expBooleanoCmpMaior_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._expBooleanoCmpMaiorIgual_ == child)
        {
            this._expBooleanoCmpMaiorIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoCmpMaior_ == oldChild)
        {
            setExpBooleanoCmpMaior((PExpBooleanoCmpMaior) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._expBooleanoCmpMaiorIgual_ == oldChild)
        {
            setExpBooleanoCmpMaiorIgual((PExpBooleanoCmpMaiorIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
