/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AComandosSeCasamento extends PSeCasamento
{
    private PComandoAlternativo _comandoAlternativo_;

    public AComandosSeCasamento()
    {
        // Constructor
    }

    public AComandosSeCasamento(
        @SuppressWarnings("hiding") PComandoAlternativo _comandoAlternativo_)
    {
        // Constructor
        setComandoAlternativo(_comandoAlternativo_);

    }

    @Override
    public Object clone()
    {
        return new AComandosSeCasamento(
            cloneNode(this._comandoAlternativo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandosSeCasamento(this);
    }

    public PComandoAlternativo getComandoAlternativo()
    {
        return this._comandoAlternativo_;
    }

    public void setComandoAlternativo(PComandoAlternativo node)
    {
        if(this._comandoAlternativo_ != null)
        {
            this._comandoAlternativo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAlternativo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoAlternativo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoAlternativo_ == child)
        {
            this._comandoAlternativo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoAlternativo_ == oldChild)
        {
            setComandoAlternativo((PComandoAlternativo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
