/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AConteudoListaListaExp extends PListaExp
{
    private PExp _exp_;
    private PSeparadorListaExp _separadorListaExp_;

    public AConteudoListaListaExp()
    {
        // Constructor
    }

    public AConteudoListaListaExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PSeparadorListaExp _separadorListaExp_)
    {
        // Constructor
        setExp(_exp_);

        setSeparadorListaExp(_separadorListaExp_);

    }

    @Override
    public Object clone()
    {
        return new AConteudoListaListaExp(
            cloneNode(this._exp_),
            cloneNode(this._separadorListaExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConteudoListaListaExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PSeparadorListaExp getSeparadorListaExp()
    {
        return this._separadorListaExp_;
    }

    public void setSeparadorListaExp(PSeparadorListaExp node)
    {
        if(this._separadorListaExp_ != null)
        {
            this._separadorListaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separadorListaExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._separadorListaExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._separadorListaExp_ == child)
        {
            this._separadorListaExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._separadorListaExp_ == oldChild)
        {
            setSeparadorListaExp((PSeparadorListaExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
