/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoVarInicioPrograma extends PInicioPrograma
{
    private PInicioPrograma _inicioPrograma_;
    private PDecVar _decVar_;

    public ADeclaracaoVarInicioPrograma()
    {
        // Constructor
    }

    public ADeclaracaoVarInicioPrograma(
        @SuppressWarnings("hiding") PInicioPrograma _inicioPrograma_,
        @SuppressWarnings("hiding") PDecVar _decVar_)
    {
        // Constructor
        setInicioPrograma(_inicioPrograma_);

        setDecVar(_decVar_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoVarInicioPrograma(
            cloneNode(this._inicioPrograma_),
            cloneNode(this._decVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoVarInicioPrograma(this);
    }

    public PInicioPrograma getInicioPrograma()
    {
        return this._inicioPrograma_;
    }

    public void setInicioPrograma(PInicioPrograma node)
    {
        if(this._inicioPrograma_ != null)
        {
            this._inicioPrograma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicioPrograma_ = node;
    }

    public PDecVar getDecVar()
    {
        return this._decVar_;
    }

    public void setDecVar(PDecVar node)
    {
        if(this._decVar_ != null)
        {
            this._decVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicioPrograma_)
            + toString(this._decVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicioPrograma_ == child)
        {
            this._inicioPrograma_ = null;
            return;
        }

        if(this._decVar_ == child)
        {
            this._decVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicioPrograma_ == oldChild)
        {
            setInicioPrograma((PInicioPrograma) newChild);
            return;
        }

        if(this._decVar_ == oldChild)
        {
            setDecVar((PDecVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
