/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADecVar extends PDecVar
{
    private TDeclVar _declVar_;
    private TDoisPontos _doisPontos_;
    private PTipo _tipo_;
    private PIdentificadorComOuSemAtribuicao _identificadorComOuSemAtribuicao_;
    private TFechaLinha _fechaLinha_;

    public ADecVar()
    {
        // Constructor
    }

    public ADecVar(
        @SuppressWarnings("hiding") TDeclVar _declVar_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") PIdentificadorComOuSemAtribuicao _identificadorComOuSemAtribuicao_,
        @SuppressWarnings("hiding") TFechaLinha _fechaLinha_)
    {
        // Constructor
        setDeclVar(_declVar_);

        setDoisPontos(_doisPontos_);

        setTipo(_tipo_);

        setIdentificadorComOuSemAtribuicao(_identificadorComOuSemAtribuicao_);

        setFechaLinha(_fechaLinha_);

    }

    @Override
    public Object clone()
    {
        return new ADecVar(
            cloneNode(this._declVar_),
            cloneNode(this._doisPontos_),
            cloneNode(this._tipo_),
            cloneNode(this._identificadorComOuSemAtribuicao_),
            cloneNode(this._fechaLinha_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecVar(this);
    }

    public TDeclVar getDeclVar()
    {
        return this._declVar_;
    }

    public void setDeclVar(TDeclVar node)
    {
        if(this._declVar_ != null)
        {
            this._declVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declVar_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public PIdentificadorComOuSemAtribuicao getIdentificadorComOuSemAtribuicao()
    {
        return this._identificadorComOuSemAtribuicao_;
    }

    public void setIdentificadorComOuSemAtribuicao(PIdentificadorComOuSemAtribuicao node)
    {
        if(this._identificadorComOuSemAtribuicao_ != null)
        {
            this._identificadorComOuSemAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificadorComOuSemAtribuicao_ = node;
    }

    public TFechaLinha getFechaLinha()
    {
        return this._fechaLinha_;
    }

    public void setFechaLinha(TFechaLinha node)
    {
        if(this._fechaLinha_ != null)
        {
            this._fechaLinha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaLinha_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declVar_)
            + toString(this._doisPontos_)
            + toString(this._tipo_)
            + toString(this._identificadorComOuSemAtribuicao_)
            + toString(this._fechaLinha_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declVar_ == child)
        {
            this._declVar_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._identificadorComOuSemAtribuicao_ == child)
        {
            this._identificadorComOuSemAtribuicao_ = null;
            return;
        }

        if(this._fechaLinha_ == child)
        {
            this._fechaLinha_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declVar_ == oldChild)
        {
            setDeclVar((TDeclVar) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._identificadorComOuSemAtribuicao_ == oldChild)
        {
            setIdentificadorComOuSemAtribuicao((PIdentificadorComOuSemAtribuicao) newChild);
            return;
        }

        if(this._fechaLinha_ == oldChild)
        {
            setFechaLinha((TFechaLinha) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
