/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADecimalValor extends PValor
{
    private TNumDecimal _numDecimal_;

    public ADecimalValor()
    {
        // Constructor
    }

    public ADecimalValor(
        @SuppressWarnings("hiding") TNumDecimal _numDecimal_)
    {
        // Constructor
        setNumDecimal(_numDecimal_);

    }

    @Override
    public Object clone()
    {
        return new ADecimalValor(
            cloneNode(this._numDecimal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecimalValor(this);
    }

    public TNumDecimal getNumDecimal()
    {
        return this._numDecimal_;
    }

    public void setNumDecimal(TNumDecimal node)
    {
        if(this._numDecimal_ != null)
        {
            this._numDecimal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numDecimal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numDecimal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numDecimal_ == child)
        {
            this._numDecimal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numDecimal_ == oldChild)
        {
            setNumDecimal((TNumDecimal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
