/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AEntradaPontoEntradaNull extends PPontoEntradaNull
{
    private TPontoEntrada _pontoEntrada_;

    public AEntradaPontoEntradaNull()
    {
        // Constructor
    }

    public AEntradaPontoEntradaNull(
        @SuppressWarnings("hiding") TPontoEntrada _pontoEntrada_)
    {
        // Constructor
        setPontoEntrada(_pontoEntrada_);

    }

    @Override
    public Object clone()
    {
        return new AEntradaPontoEntradaNull(
            cloneNode(this._pontoEntrada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEntradaPontoEntradaNull(this);
    }

    public TPontoEntrada getPontoEntrada()
    {
        return this._pontoEntrada_;
    }

    public void setPontoEntrada(TPontoEntrada node)
    {
        if(this._pontoEntrada_ != null)
        {
            this._pontoEntrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEntrada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pontoEntrada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pontoEntrada_ == child)
        {
            this._pontoEntrada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pontoEntrada_ == oldChild)
        {
            setPontoEntrada((TPontoEntrada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
