/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpBooleanoCmpExpNegacao extends PExpNegacao
{
    private PExpBooleanoCmp _expBooleanoCmp_;

    public AExpBooleanoCmpExpNegacao()
    {
        // Constructor
    }

    public AExpBooleanoCmpExpNegacao(
        @SuppressWarnings("hiding") PExpBooleanoCmp _expBooleanoCmp_)
    {
        // Constructor
        setExpBooleanoCmp(_expBooleanoCmp_);

    }

    @Override
    public Object clone()
    {
        return new AExpBooleanoCmpExpNegacao(
            cloneNode(this._expBooleanoCmp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpBooleanoCmpExpNegacao(this);
    }

    public PExpBooleanoCmp getExpBooleanoCmp()
    {
        return this._expBooleanoCmp_;
    }

    public void setExpBooleanoCmp(PExpBooleanoCmp node)
    {
        if(this._expBooleanoCmp_ != null)
        {
            this._expBooleanoCmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoCmp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoCmp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoCmp_ == child)
        {
            this._expBooleanoCmp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoCmp_ == oldChild)
        {
            setExpBooleanoCmp((PExpBooleanoCmp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
