/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpValExpTernario extends PExpTernario
{
    private PExpNegativo _expNegativo_;

    public AExpValExpTernario()
    {
        // Constructor
    }

    public AExpValExpTernario(
        @SuppressWarnings("hiding") PExpNegativo _expNegativo_)
    {
        // Constructor
        setExpNegativo(_expNegativo_);

    }

    @Override
    public Object clone()
    {
        return new AExpValExpTernario(
            cloneNode(this._expNegativo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpValExpTernario(this);
    }

    public PExpNegativo getExpNegativo()
    {
        return this._expNegativo_;
    }

    public void setExpNegativo(PExpNegativo node)
    {
        if(this._expNegativo_ != null)
        {
            this._expNegativo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expNegativo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expNegativo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expNegativo_ == child)
        {
            this._expNegativo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expNegativo_ == oldChild)
        {
            setExpNegativo((PExpNegativo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
