/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpOpMultExpSubtracao extends PExpSubtracao
{
    private PExpOpMult _expOpMult_;

    public AExpOpMultExpSubtracao()
    {
        // Constructor
    }

    public AExpOpMultExpSubtracao(
        @SuppressWarnings("hiding") PExpOpMult _expOpMult_)
    {
        // Constructor
        setExpOpMult(_expOpMult_);

    }

    @Override
    public Object clone()
    {
        return new AExpOpMultExpSubtracao(
            cloneNode(this._expOpMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpOpMultExpSubtracao(this);
    }

    public PExpOpMult getExpOpMult()
    {
        return this._expOpMult_;
    }

    public void setExpOpMult(PExpOpMult node)
    {
        if(this._expOpMult_ != null)
        {
            this._expOpMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOpMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOpMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOpMult_ == child)
        {
            this._expOpMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOpMult_ == oldChild)
        {
            setExpOpMult((PExpOpMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
