/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpMaiorExpBooleanoCmpMaiorIgual extends PExpBooleanoCmpMaiorIgual
{
    private PExpBooleanoCmpIgual _expBooleanoCmpIgual_;

    public AExpMaiorExpBooleanoCmpMaiorIgual()
    {
        // Constructor
    }

    public AExpMaiorExpBooleanoCmpMaiorIgual(
        @SuppressWarnings("hiding") PExpBooleanoCmpIgual _expBooleanoCmpIgual_)
    {
        // Constructor
        setExpBooleanoCmpIgual(_expBooleanoCmpIgual_);

    }

    @Override
    public Object clone()
    {
        return new AExpMaiorExpBooleanoCmpMaiorIgual(
            cloneNode(this._expBooleanoCmpIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMaiorExpBooleanoCmpMaiorIgual(this);
    }

    public PExpBooleanoCmpIgual getExpBooleanoCmpIgual()
    {
        return this._expBooleanoCmpIgual_;
    }

    public void setExpBooleanoCmpIgual(PExpBooleanoCmpIgual node)
    {
        if(this._expBooleanoCmpIgual_ != null)
        {
            this._expBooleanoCmpIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoCmpIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoCmpIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoCmpIgual_ == child)
        {
            this._expBooleanoCmpIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoCmpIgual_ == oldChild)
        {
            setExpBooleanoCmpIgual((PExpBooleanoCmpIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
