/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpNegativoExpNegativo extends PExpNegativo
{
    private TMenos _menos_;
    private PExpNegativo _expNegativo_;

    public AExpNegativoExpNegativo()
    {
        // Constructor
    }

    public AExpNegativoExpNegativo(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpNegativo _expNegativo_)
    {
        // Constructor
        setMenos(_menos_);

        setExpNegativo(_expNegativo_);

    }

    @Override
    public Object clone()
    {
        return new AExpNegativoExpNegativo(
            cloneNode(this._menos_),
            cloneNode(this._expNegativo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpNegativoExpNegativo(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpNegativo getExpNegativo()
    {
        return this._expNegativo_;
    }

    public void setExpNegativo(PExpNegativo node)
    {
        if(this._expNegativo_ != null)
        {
            this._expNegativo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expNegativo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._expNegativo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expNegativo_ == child)
        {
            this._expNegativo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expNegativo_ == oldChild)
        {
            setExpNegativo((PExpNegativo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
