/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpBooleanoCmpMaiorExpNegacao extends PExpNegacao
{
    private PExpBooleanoCmpMaior _expBooleanoCmpMaior_;

    public AExpBooleanoCmpMaiorExpNegacao()
    {
        // Constructor
    }

    public AExpBooleanoCmpMaiorExpNegacao(
        @SuppressWarnings("hiding") PExpBooleanoCmpMaior _expBooleanoCmpMaior_)
    {
        // Constructor
        setExpBooleanoCmpMaior(_expBooleanoCmpMaior_);

    }

    @Override
    public Object clone()
    {
        return new AExpBooleanoCmpMaiorExpNegacao(
            cloneNode(this._expBooleanoCmpMaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpBooleanoCmpMaiorExpNegacao(this);
    }

    public PExpBooleanoCmpMaior getExpBooleanoCmpMaior()
    {
        return this._expBooleanoCmpMaior_;
    }

    public void setExpBooleanoCmpMaior(PExpBooleanoCmpMaior node)
    {
        if(this._expBooleanoCmpMaior_ != null)
        {
            this._expBooleanoCmpMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoCmpMaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoCmpMaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoCmpMaior_ == child)
        {
            this._expBooleanoCmpMaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoCmpMaior_ == oldChild)
        {
            setExpBooleanoCmpMaior((PExpBooleanoCmpMaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
