/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpSomaExpBooleanoOu extends PExpBooleanoOu
{
    private PExpBooleanoE _expBooleanoE_;

    public AExpSomaExpBooleanoOu()
    {
        // Constructor
    }

    public AExpSomaExpBooleanoOu(
        @SuppressWarnings("hiding") PExpBooleanoE _expBooleanoE_)
    {
        // Constructor
        setExpBooleanoE(_expBooleanoE_);

    }

    @Override
    public Object clone()
    {
        return new AExpSomaExpBooleanoOu(
            cloneNode(this._expBooleanoE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpSomaExpBooleanoOu(this);
    }

    public PExpBooleanoE getExpBooleanoE()
    {
        return this._expBooleanoE_;
    }

    public void setExpBooleanoE(PExpBooleanoE node)
    {
        if(this._expBooleanoE_ != null)
        {
            this._expBooleanoE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBooleanoE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBooleanoE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBooleanoE_ == child)
        {
            this._expBooleanoE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBooleanoE_ == oldChild)
        {
            setExpBooleanoE((PExpBooleanoE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
