/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMenosSubtracaoExpSubtracao extends PExpSubtracao
{
    private PExpSubtracao _expSubtracao_;
    private TMenos _menos_;
    private PExpOpMult _expOpMult_;

    public AMenosSubtracaoExpSubtracao()
    {
        // Constructor
    }

    public AMenosSubtracaoExpSubtracao(
        @SuppressWarnings("hiding") PExpSubtracao _expSubtracao_,
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpOpMult _expOpMult_)
    {
        // Constructor
        setExpSubtracao(_expSubtracao_);

        setMenos(_menos_);

        setExpOpMult(_expOpMult_);

    }

    @Override
    public Object clone()
    {
        return new AMenosSubtracaoExpSubtracao(
            cloneNode(this._expSubtracao_),
            cloneNode(this._menos_),
            cloneNode(this._expOpMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosSubtracaoExpSubtracao(this);
    }

    public PExpSubtracao getExpSubtracao()
    {
        return this._expSubtracao_;
    }

    public void setExpSubtracao(PExpSubtracao node)
    {
        if(this._expSubtracao_ != null)
        {
            this._expSubtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSubtracao_ = node;
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpOpMult getExpOpMult()
    {
        return this._expOpMult_;
    }

    public void setExpOpMult(PExpOpMult node)
    {
        if(this._expOpMult_ != null)
        {
            this._expOpMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOpMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSubtracao_)
            + toString(this._menos_)
            + toString(this._expOpMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSubtracao_ == child)
        {
            this._expSubtracao_ = null;
            return;
        }

        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expOpMult_ == child)
        {
            this._expOpMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSubtracao_ == oldChild)
        {
            setExpSubtracao((PExpSubtracao) newChild);
            return;
        }

        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expOpMult_ == oldChild)
        {
            setExpOpMult((PExpOpMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
