/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicacaoExpOpMult extends PExpOpMult
{
    private PExpOpMult _expOpMult_;
    private TMult _mult_;
    private PExpTernario _expTernario_;

    public AMultiplicacaoExpOpMult()
    {
        // Constructor
    }

    public AMultiplicacaoExpOpMult(
        @SuppressWarnings("hiding") PExpOpMult _expOpMult_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PExpTernario _expTernario_)
    {
        // Constructor
        setExpOpMult(_expOpMult_);

        setMult(_mult_);

        setExpTernario(_expTernario_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicacaoExpOpMult(
            cloneNode(this._expOpMult_),
            cloneNode(this._mult_),
            cloneNode(this._expTernario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicacaoExpOpMult(this);
    }

    public PExpOpMult getExpOpMult()
    {
        return this._expOpMult_;
    }

    public void setExpOpMult(PExpOpMult node)
    {
        if(this._expOpMult_ != null)
        {
            this._expOpMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOpMult_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PExpTernario getExpTernario()
    {
        return this._expTernario_;
    }

    public void setExpTernario(PExpTernario node)
    {
        if(this._expTernario_ != null)
        {
            this._expTernario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTernario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOpMult_)
            + toString(this._mult_)
            + toString(this._expTernario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOpMult_ == child)
        {
            this._expOpMult_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._expTernario_ == child)
        {
            this._expTernario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOpMult_ == oldChild)
        {
            setExpOpMult((PExpOpMult) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._expTernario_ == oldChild)
        {
            setExpTernario((PExpTernario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
