/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ANullPontoEntradaNull extends PPontoEntradaNull
{

    public ANullPontoEntradaNull()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANullPontoEntradaNull();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANullPontoEntradaNull(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
