/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ANumBinarioValor extends PValor
{
    private TNumBinario _numBinario_;

    public ANumBinarioValor()
    {
        // Constructor
    }

    public ANumBinarioValor(
        @SuppressWarnings("hiding") TNumBinario _numBinario_)
    {
        // Constructor
        setNumBinario(_numBinario_);

    }

    @Override
    public Object clone()
    {
        return new ANumBinarioValor(
            cloneNode(this._numBinario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumBinarioValor(this);
    }

    public TNumBinario getNumBinario()
    {
        return this._numBinario_;
    }

    public void setNumBinario(TNumBinario node)
    {
        if(this._numBinario_ != null)
        {
            this._numBinario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numBinario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numBinario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numBinario_ == child)
        {
            this._numBinario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numBinario_ == oldChild)
        {
            setNumBinario((TNumBinario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
