/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AOp2ExpOpSoma extends PExpOpSoma
{
    private PExpSubtracao _expSubtracao_;

    public AOp2ExpOpSoma()
    {
        // Constructor
    }

    public AOp2ExpOpSoma(
        @SuppressWarnings("hiding") PExpSubtracao _expSubtracao_)
    {
        // Constructor
        setExpSubtracao(_expSubtracao_);

    }

    @Override
    public Object clone()
    {
        return new AOp2ExpOpSoma(
            cloneNode(this._expSubtracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOp2ExpOpSoma(this);
    }

    public PExpSubtracao getExpSubtracao()
    {
        return this._expSubtracao_;
    }

    public void setExpSubtracao(PExpSubtracao node)
    {
        if(this._expSubtracao_ != null)
        {
            this._expSubtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSubtracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSubtracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSubtracao_ == child)
        {
            this._expSubtracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSubtracao_ == oldChild)
        {
            setExpSubtracao((PExpSubtracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
