/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AParamParametros extends PParametros
{
    private PParametro _parametro_;
    private PFechoParametros _fechoParametros_;

    public AParamParametros()
    {
        // Constructor
    }

    public AParamParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") PFechoParametros _fechoParametros_)
    {
        // Constructor
        setParametro(_parametro_);

        setFechoParametros(_fechoParametros_);

    }

    @Override
    public Object clone()
    {
        return new AParamParametros(
            cloneNode(this._parametro_),
            cloneNode(this._fechoParametros_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public PFechoParametros getFechoParametros()
    {
        return this._fechoParametros_;
    }

    public void setFechoParametros(PFechoParametros node)
    {
        if(this._fechoParametros_ != null)
        {
            this._fechoParametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechoParametros_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._fechoParametros_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._fechoParametros_ == child)
        {
            this._fechoParametros_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        if(this._fechoParametros_ == oldChild)
        {
            setFechoParametros((PFechoParametros) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
