/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AParamFechoParametros extends PFechoParametros
{
    private PFechoParametros _fechoParametros_;
    private TSeparador _separador_;
    private PParametro _parametro_;

    public AParamFechoParametros()
    {
        // Constructor
    }

    public AParamFechoParametros(
        @SuppressWarnings("hiding") PFechoParametros _fechoParametros_,
        @SuppressWarnings("hiding") TSeparador _separador_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setFechoParametros(_fechoParametros_);

        setSeparador(_separador_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AParamFechoParametros(
            cloneNode(this._fechoParametros_),
            cloneNode(this._separador_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamFechoParametros(this);
    }

    public PFechoParametros getFechoParametros()
    {
        return this._fechoParametros_;
    }

    public void setFechoParametros(PFechoParametros node)
    {
        if(this._fechoParametros_ != null)
        {
            this._fechoParametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechoParametros_ = node;
    }

    public TSeparador getSeparador()
    {
        return this._separador_;
    }

    public void setSeparador(TSeparador node)
    {
        if(this._separador_ != null)
        {
            this._separador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separador_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fechoParametros_)
            + toString(this._separador_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fechoParametros_ == child)
        {
            this._fechoParametros_ = null;
            return;
        }

        if(this._separador_ == child)
        {
            this._separador_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fechoParametros_ == oldChild)
        {
            setFechoParametros((PFechoParametros) newChild);
            return;
        }

        if(this._separador_ == oldChild)
        {
            setSeparador((TSeparador) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
