/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ASeNaoCasadoComando extends PComando
{
    private PSeSemCasamento _seSemCasamento_;

    public ASeNaoCasadoComando()
    {
        // Constructor
    }

    public ASeNaoCasadoComando(
        @SuppressWarnings("hiding") PSeSemCasamento _seSemCasamento_)
    {
        // Constructor
        setSeSemCasamento(_seSemCasamento_);

    }

    @Override
    public Object clone()
    {
        return new ASeNaoCasadoComando(
            cloneNode(this._seSemCasamento_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeNaoCasadoComando(this);
    }

    public PSeSemCasamento getSeSemCasamento()
    {
        return this._seSemCasamento_;
    }

    public void setSeSemCasamento(PSeSemCasamento node)
    {
        if(this._seSemCasamento_ != null)
        {
            this._seSemCasamento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seSemCasamento_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seSemCasamento_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seSemCasamento_ == child)
        {
            this._seSemCasamento_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seSemCasamento_ == oldChild)
        {
            setSeSemCasamento((PSeSemCasamento) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
