/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExpOpSoma extends PExpOpSoma
{
    private PExpOpSoma _expOpSoma_;
    private TSoma _soma_;
    private PExpSubtracao _expSubtracao_;

    public ASomaExpOpSoma()
    {
        // Constructor
    }

    public ASomaExpOpSoma(
        @SuppressWarnings("hiding") PExpOpSoma _expOpSoma_,
        @SuppressWarnings("hiding") TSoma _soma_,
        @SuppressWarnings("hiding") PExpSubtracao _expSubtracao_)
    {
        // Constructor
        setExpOpSoma(_expOpSoma_);

        setSoma(_soma_);

        setExpSubtracao(_expSubtracao_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpOpSoma(
            cloneNode(this._expOpSoma_),
            cloneNode(this._soma_),
            cloneNode(this._expSubtracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpOpSoma(this);
    }

    public PExpOpSoma getExpOpSoma()
    {
        return this._expOpSoma_;
    }

    public void setExpOpSoma(PExpOpSoma node)
    {
        if(this._expOpSoma_ != null)
        {
            this._expOpSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOpSoma_ = node;
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PExpSubtracao getExpSubtracao()
    {
        return this._expSubtracao_;
    }

    public void setExpSubtracao(PExpSubtracao node)
    {
        if(this._expSubtracao_ != null)
        {
            this._expSubtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSubtracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOpSoma_)
            + toString(this._soma_)
            + toString(this._expSubtracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOpSoma_ == child)
        {
            this._expOpSoma_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._expSubtracao_ == child)
        {
            this._expSubtracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOpSoma_ == oldChild)
        {
            setExpOpSoma((PExpOpSoma) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        if(this._expSubtracao_ == oldChild)
        {
            setExpSubtracao((PExpSubtracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
