/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ATernarioExpTernario extends PExpTernario
{
    private TSe _se_;
    private TParEsq _parEsq_;
    private PExp _condicao_;
    private TParDir _parDir_;
    private PExp _valorSeVerdadeiro_;
    private TSenao _senao_;
    private PExpTernario _valorSeFalso_;

    public ATernarioExpTernario()
    {
        // Constructor
    }

    public ATernarioExpTernario(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExp _condicao_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PExp _valorSeVerdadeiro_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PExpTernario _valorSeFalso_)
    {
        // Constructor
        setSe(_se_);

        setParEsq(_parEsq_);

        setCondicao(_condicao_);

        setParDir(_parDir_);

        setValorSeVerdadeiro(_valorSeVerdadeiro_);

        setSenao(_senao_);

        setValorSeFalso(_valorSeFalso_);

    }

    @Override
    public Object clone()
    {
        return new ATernarioExpTernario(
            cloneNode(this._se_),
            cloneNode(this._parEsq_),
            cloneNode(this._condicao_),
            cloneNode(this._parDir_),
            cloneNode(this._valorSeVerdadeiro_),
            cloneNode(this._senao_),
            cloneNode(this._valorSeFalso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernarioExpTernario(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExp getCondicao()
    {
        return this._condicao_;
    }

    public void setCondicao(PExp node)
    {
        if(this._condicao_ != null)
        {
            this._condicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicao_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PExp getValorSeVerdadeiro()
    {
        return this._valorSeVerdadeiro_;
    }

    public void setValorSeVerdadeiro(PExp node)
    {
        if(this._valorSeVerdadeiro_ != null)
        {
            this._valorSeVerdadeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorSeVerdadeiro_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PExpTernario getValorSeFalso()
    {
        return this._valorSeFalso_;
    }

    public void setValorSeFalso(PExpTernario node)
    {
        if(this._valorSeFalso_ != null)
        {
            this._valorSeFalso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorSeFalso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._parEsq_)
            + toString(this._condicao_)
            + toString(this._parDir_)
            + toString(this._valorSeVerdadeiro_)
            + toString(this._senao_)
            + toString(this._valorSeFalso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._condicao_ == child)
        {
            this._condicao_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._valorSeVerdadeiro_ == child)
        {
            this._valorSeVerdadeiro_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._valorSeFalso_ == child)
        {
            this._valorSeFalso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._condicao_ == oldChild)
        {
            setCondicao((PExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._valorSeVerdadeiro_ == oldChild)
        {
            setValorSeVerdadeiro((PExp) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._valorSeFalso_ == oldChild)
        {
            setValorSeFalso((PExpTernario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
