/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TExpFecha extends Token
{
    public TExpFecha()
    {
        super.setText("termine");
    }

    public TExpFecha(int line, int pos)
    {
        super.setText("termine");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExpFecha(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExpFecha(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExpFecha text.");
    }
}
