/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TVerdadeiro extends Token
{
    public TVerdadeiro()
    {
        super.setText("verdade");
    }

    public TVerdadeiro(int line, int pos)
    {
        super.setText("verdade");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVerdadeiro(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVerdadeiro(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVerdadeiro text.");
    }
}
